<?php
defined( '_JEXEC' ) or die( 'Restricted access' );

$q = strtolower($_REQUEST["q"]);
if (!$q) return;
$items = array(
"1"=>"Algeria",
"2"=>"Argentina",
"3"=>"Australia",
"4"=>"Austria",
"5"=>"Belgium",
"7"=>"Bolivia",
"8"=>"Bosnia",
"9"=>"Brazil",
"10"=>"Bulgaria",
"11"=>"Canada",
"12"=>"Caribbean Islands",
"13"=>"Chile",
"14"=>"China",
"15"=>"Colombia",
"16"=>"Costa Rica",
"17"=>"Croatia",
"18"=>"Cyprus",
"19"=>"Czech Republic",
"20"=>"Denmark",
"21"=>"Dominican Republic",
"22"=>"Ecuador",
"23"=>"Egypt",
"24"=>"El Salvador",
"26"=>"Estonia",
"28"=>"Finland",
"29"=>"France",
"30"=>"Germany",
"31"=>"Greece",
"32"=>"Guatemala",
"33"=>"Haiti",
"34"=>"Honduras",
"35"=>"Hungary",
"36"=>"Iceland",
"37"=>"India",
"38"=>"Indonesia",
"39"=>"Iran",
"40"=>"Ireland",
"41"=>"Israel",
"42"=>"Italy",
"43"=>"Ivory Coast",
"44"=>"Japan",
"45"=>"Jordan",
"46"=>"Kenya",
"47"=>"Kuwait",
"48"=>"Latvia",
"49"=>"Lebanon",
"50"=>"Libya",
"51"=>"Lithuania",
"52"=>"Luxembourg",
"53"=>"Macedonia",
"54"=>"Malaysia",
"55"=>"Malta",
"56"=>"Mauritius",
"57"=>"Mexico",
"58"=>"Moldavia",
"59"=>"Morocco",
"60"=>"Netherlands",
"61"=>"New Zealand",
"62"=>"Nicaragua",
"63"=>"Nigeria",
"64"=>"Norway",
"65"=>"Oman",
"66"=>"Pakistan",
"67"=>"Panama",
"68"=>"Paraguay",
"69"=>"Peru",
"70"=>"Philippines",
"71"=>"Poland",
"72"=>"Portugal",
"73"=>"Puerto Rico",
"74"=>"Romania",
"75"=>"Russia",
"76"=>"Saudi Arabia",
"77"=>"Singapore",
"78"=>"Slovakia",
"79"=>"Slovenia",
"80"=>"South Africa",
"81"=>"South Korea",
"82"=>"Spain",
"83"=>"Sri Lanka",
"84"=>"Sweden",
"85"=>"Switzerland",
"86"=>"Taiwan",
"87"=>"Thailand",
"88"=>"Tunisia",
"89"=>"Turkey",
"90"=>"UAE",
"92"=>"Ukraine",
"91"=>"United Kingdom",
"93"=>"Uruguay",
"94"=>"USA",
"95"=>"Venezuela",
"96"=>"Vietnam",
"97"=>"West Africa",
"98"=>"Yemen",
"99"=>"Yugoslavia",
"100"=>"Zimbabwe"
);

$json = array();

foreach ($items as $key=>$value) {
	if (strpos(strtolower($value), $q) !== false) {
		$json[] = '"' . $value . '"';
	}
}

echo '[' . implode(',', $json) . ']';

?>
