-- --------------------------------------------------------
--
-- Table structure for table '#__joomleague_match_single'
--
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS #__joomleague_match_single (
  id int(11) NOT NULL AUTO_INCREMENT,
  round_id int(11) NOT NULL DEFAULT '0',
  match_number varchar(10) DEFAULT NULL,
  projectteam1_id int(11) NOT NULL DEFAULT '0',
  projectteam2_id int(11) NOT NULL DEFAULT '0',
  playground_id int(11) DEFAULT NULL,
  match_id int(11) NOT NULL,
  teamplayer1_id int(11) NOT NULL,
  teamplayer2_id int(11) NOT NULL,
  match_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  time_present time DEFAULT NULL,
  team1_result float DEFAULT NULL,
  team2_result float DEFAULT NULL,
  team1_bonus int(11) DEFAULT NULL,
  team2_bonus int(11) DEFAULT NULL,
  team1_legs float DEFAULT NULL,
  team2_legs float DEFAULT NULL,
  team1_result_split varchar(64) DEFAULT NULL,
  team2_result_split varchar(64) DEFAULT NULL,
  match_result_type tinyint(4) NOT NULL DEFAULT '0',
  team_won tinyint(4) NOT NULL DEFAULT '0',
  team1_result_ot float DEFAULT NULL,
  team2_result_ot float DEFAULT NULL,
  team1_result_so float DEFAULT NULL,
  team2_result_so float DEFAULT NULL,
  alt_decision tinyint(4) NOT NULL DEFAULT '0',
  team1_result_decision float DEFAULT NULL,
  team2_result_decision float DEFAULT NULL,
  decision_info varchar(128) NOT NULL DEFAULT '',
  cancel tinyint(4) NOT NULL DEFAULT '0',
  cancel_reason varchar(32) NOT NULL DEFAULT '',
  count_result tinyint(4) NOT NULL DEFAULT '1',
  crowd int(11) NOT NULL DEFAULT '0',
  summary text NOT NULL,
  show_report tinyint(4) NOT NULL DEFAULT '0',
  preview text NOT NULL,
  match_result_detail varchar(64) NOT NULL DEFAULT '',
  new_match_id int(11) NOT NULL DEFAULT '0',
  old_match_id int(11) NOT NULL DEFAULT '0',
  `extended` text,
  published tinyint(4) NOT NULL DEFAULT '0',
  modified datetime DEFAULT NULL,
  modified_by int(11) DEFAULT NULL,
  checked_out int(11) NOT NULL DEFAULT '0',
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id),
  KEY round_id (round_id),
  KEY projectteam1_id (projectteam1_id),
  KEY projectteam2_id (projectteam2_id),
  KEY playground_id (playground_id),
  KEY new_match_id (new_match_id),
  KEY old_match_id (old_match_id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
