<?php
/**
 * Joomla 5/6 native project match-statistic XML import service.
 *
 * @version    5.6.0
 * @author     diddipoeler
 * @copyright  Copyright (C) diddipoeler
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */
namespace Diddipoeler\Component\SportsManagement\Administrator\Service;

\defined('_JEXEC') or die;

use Joomla\Database\DatabaseInterface;
use Joomla\Database\ParameterType;
use RuntimeException;

/**
 * Native writer for project XML import steps 31-32.
 *
 * These rows deliberately resolve the final season_team_person_id generated by
 * the project finalizer instead of storing the temporary team_player/team_staff
 * IDs which are truncated at the end of the historical import workflow.
 */
final class XmlProjectMatchStatisticImportService
{
    public function __construct(private readonly DatabaseInterface $database)
    {
    }

    /**
     * @param array<string, mixed> $parsedData
     * @param array<int, int> $matchMap
     * @param array<int, int> $projectTeamMap
     * @param array<int, int> $personMap
     * @param array<int, int> $statisticMap
     *
     * @return array{messages:array<string,string>}
     */
    public function import(
        array $parsedData,
        int $seasonId,
        array $matchMap,
        array $projectTeamMap,
        array $personMap,
        array $statisticMap,
        string $step
    ): array {
        $messages = [];

        if (version_compare($step, '31', 'ge')) {
            $messages['Importing match staff statistic data:'] = $this->importCollection(
                (array) ($parsedData['matchstaffstatistic'] ?? []),
                (array) ($parsedData['teamstaff'] ?? []),
                '#__sportsmanagement_match_staff_statistic',
                'team_staff_id',
                2,
                $seasonId,
                $matchMap,
                $projectTeamMap,
                $personMap,
                $statisticMap,
                'match-staff-statistic'
            );
        }

        if (version_compare($step, '32', 'ge')) {
            $messages['Importing match statistic data:'] = $this->importCollection(
                (array) ($parsedData['matchstatistic'] ?? []),
                (array) ($parsedData['teamplayer'] ?? []),
                '#__sportsmanagement_match_statistic',
                'teamplayer_id',
                1,
                $seasonId,
                $matchMap,
                $projectTeamMap,
                $personMap,
                $statisticMap,
                'match-statistic'
            );
        }

        return ['messages' => $messages];
    }

    /**
     * @param array<int|string, mixed> $statistics
     * @param array<int|string, mixed> $members
     * @param array<int, int> $matchMap
     * @param array<int, int> $projectTeamMap
     * @param array<int, int> $personMap
     * @param array<int, int> $statisticMap
     */
    private function importCollection(
        array $statistics,
        array $members,
        string $table,
        string $memberField,
        int $personType,
        int $seasonId,
        array $matchMap,
        array $projectTeamMap,
        array $personMap,
        array $statisticMap,
        string $label
    ): string {
        $memberSources = $this->indexBySourceId($members);
        $message = '';

        foreach (array_values($statistics) as $source) {
            if (!is_object($source)) {
                continue;
            }

            $oldId = max(0, (int) ($source->id ?? 0));
            $oldMatchId = max(0, (int) ($source->match_id ?? 0));
            $oldProjectTeamId = max(0, (int) ($source->projectteam_id ?? 0));
            $oldStatisticId = max(0, (int) ($source->statistic_id ?? 0));
            $oldMemberId = max(0, (int) ($source->{$memberField} ?? 0));
            $memberSource = $memberSources[$oldMemberId] ?? null;

            $matchId = (int) ($matchMap[$oldMatchId] ?? 0);
            $projectTeamId = (int) ($projectTeamMap[$oldProjectTeamId] ?? 0);
            $statisticId = (int) ($statisticMap[$oldStatisticId] ?? 0);
            $finalMemberId = is_object($memberSource)
                ? $this->resolveFinalMemberId(
                    $memberSource,
                    $seasonId,
                    $personType,
                    $projectTeamMap,
                    $personMap
                )
                : 0;

            if ($matchId <= 0 || $projectTeamId <= 0 || $statisticId <= 0 || $finalMemberId <= 0) {
                $message .= $this->skippedMessage($label, $oldId);
                continue;
            }

            $row = (object) [
                'match_id' => $matchId,
                'projectteam_id' => $projectTeamId,
                $memberField => $finalMemberId,
                'statistic_id' => $statisticId,
                'value' => $source->value ?? 0,
            ];

            if (!$this->database->insertObject($table, $row)) {
                throw new RuntimeException('Unable to store imported ' . $label . ' ID ' . $oldId . '.', 500);
            }

            $message .= $this->createdMessage($label, $oldId, $finalMemberId);
        }

        return $message;
    }

    /**
     * @param array<int|string, mixed> $members
     * @return array<int, object>
     */
    private function indexBySourceId(array $members): array
    {
        $result = [];

        foreach ($members as $source) {
            if (!is_object($source)) {
                continue;
            }

            $oldId = max(0, (int) ($source->id ?? 0));

            if ($oldId > 0) {
                $result[$oldId] = $source;
            }
        }

        return $result;
    }

    /**
     * @param array<int, int> $projectTeamMap
     * @param array<int, int> $personMap
     */
    private function resolveFinalMemberId(
        object $source,
        int $seasonId,
        int $personType,
        array $projectTeamMap,
        array $personMap
    ): int {
        $oldProjectTeamId = max(0, (int) ($source->projectteam_id ?? 0));
        $oldPersonId = max(0, (int) ($source->person_id ?? 0));
        $projectTeamId = (int) ($projectTeamMap[$oldProjectTeamId] ?? 0);
        $personId = (int) ($personMap[$oldPersonId] ?? 0);

        if ($seasonId <= 0 || $projectTeamId <= 0 || $personId <= 0) {
            return 0;
        }

        $query = $this->database->createQuery()
            ->select($this->database->quoteName('st.team_id'))
            ->from($this->database->quoteName('#__sportsmanagement_project_team', 'pt'))
            ->join(
                'INNER',
                $this->database->quoteName('#__sportsmanagement_season_team_id', 'st')
                . ' ON ' . $this->database->quoteName('st.id') . ' = ' . $this->database->quoteName('pt.team_id')
            )
            ->where($this->database->quoteName('pt.id') . ' = :projectTeamId')
            ->where($this->database->quoteName('st.season_id') . ' = :seasonId')
            ->bind(':projectTeamId', $projectTeamId, ParameterType::INTEGER)
            ->bind(':seasonId', $seasonId, ParameterType::INTEGER);
        $this->database->setQuery($query, 0, 1);
        $teamId = (int) ($this->database->loadResult() ?? 0);

        if ($teamId <= 0) {
            return 0;
        }

        $query = $this->database->createQuery()
            ->select($this->database->quoteName('id'))
            ->from($this->database->quoteName('#__sportsmanagement_season_team_person_id'))
            ->where($this->database->quoteName('person_id') . ' = :personId')
            ->where($this->database->quoteName('season_id') . ' = :seasonId')
            ->where($this->database->quoteName('team_id') . ' = :teamId')
            ->where($this->database->quoteName('persontype') . ' IN (0, ' . $personType . ')')
            ->bind(':personId', $personId, ParameterType::INTEGER)
            ->bind(':seasonId', $seasonId, ParameterType::INTEGER)
            ->bind(':teamId', $teamId, ParameterType::INTEGER);
        $this->database->setQuery($query, 0, 1);

        return (int) ($this->database->loadResult() ?? 0);
    }

    private function createdMessage(string $label, int $oldId, int $memberId): string
    {
        return '<span style="color:green">Created new ' . htmlspecialchars($label, ENT_QUOTES, 'UTF-8')
            . ' data: </span><strong>' . htmlspecialchars((string) $oldId, ENT_QUOTES, 'UTF-8')
            . '</strong> / Seasonal member <strong>'
            . htmlspecialchars((string) $memberId, ENT_QUOTES, 'UTF-8') . '</strong><br />';
    }

    private function skippedMessage(string $label, int $oldId): string
    {
        return '<span style="color:red">Skipping ' . htmlspecialchars($label, ENT_QUOTES, 'UTF-8')
            . ' ID <strong>' . htmlspecialchars((string) $oldId, ENT_QUOTES, 'UTF-8')
            . '</strong>; final match/member/statistic mapping is unavailable.</span><br />';
    }
}
