-- ALTER TABLE  `#__sportsmanagement_person` ADD  `bank_code_number` VARCHAR( 100 ) NULL DEFAULT  '';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `bank_account_number` VARCHAR( 100 ) NULL DEFAULT  '';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `iban` VARCHAR( 100 ) NULL DEFAULT  '';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `bank_identifier_code` VARCHAR( 100 ) NULL DEFAULT  '';
