-- ALTER TABLE  `#__sportsmanagement_league` ADD  `sports_type_id` TINYINT( 1 ) NOT NULL DEFAULT  '1';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `sports_type_id` TINYINT( 1 ) NOT NULL DEFAULT  '1';
