-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team1_single_matchpoint` DOUBLE NULL DEFAULT NULL ;
-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team2_single_matchpoint` DOUBLE NULL DEFAULT NULL ;
-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team1_single_sets` DOUBLE NULL DEFAULT NULL ;
-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team2_single_sets` DOUBLE NULL DEFAULT NULL ;
-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team1_single_games` DOUBLE NULL DEFAULT NULL ;
-- ALTER TABLE  `#__sportsmanagement_match` ADD  `team2_single_games` DOUBLE NULL DEFAULT NULL ;
