-- ALTER TABLE  `#__sportsmanagement_person` ADD  `person_id1` INT( 11 ) NOT NULL DEFAULT  '0';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `person_id2` INT( 11 ) NOT NULL DEFAULT  '0';
-- ALTER TABLE  `#__sportsmanagement_person` ADD  `person_art` TINYINT( 4 ) NOT NULL DEFAULT  '1';
