-- ALTER TABLE  `#__sportsmanagement_season_person_id` ADD  `picture` VARCHAR( 250 ) NULL ;
-- ALTER TABLE  `#__sportsmanagement_season_team_id` ADD  `picture` VARCHAR( 250 ) NULL ;
-- ALTER TABLE  `#__sportsmanagement_season_team_id` ADD  `logo_big` VARCHAR( 250 ) NULL ;
