<?php
\defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
$user = $this->getCurrentUser(); $listOrder = (string) $this->state->get('list.ordering', 's.name'); $listDirn = (string) $this->state->get('list.direction', 'ASC');
?>
<form action="<?php echo Route::_('index.php?option=com_sportsmanagement&view=sportstypes'); ?>" method="post" name="adminForm" id="adminForm">
<?php if ($this->filterForm) echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]); ?>
<div class="table-responsive"><table class="table table-striped" id="sportstypesList"><thead><tr><th class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></th><th><?php echo HTMLHelper::_('searchtools.sort','COM_SPORTSMANAGEMENT_ADMIN_SPORTSTYPES_NAME','s.name',$listDirn,$listOrder); ?></th><th class="text-center"><?php echo Text::_('COM_SPORTSMANAGEMENT_ADMIN_SPORTSTYPES_ICON'); ?></th><th class="text-center"><?php echo HTMLHelper::_('searchtools.sort','COM_SPORTSMANAGEMENT_ADMIN_SPORTSTYPES_SPORTSART','s.sportsart',$listDirn,$listOrder); ?></th><th class="w-10 text-center"><?php echo HTMLHelper::_('searchtools.sort','JSTATUS','s.published',$listDirn,$listOrder); ?></th><th class="w-10 text-center"><?php echo HTMLHelper::_('searchtools.sort','JGRID_HEADING_ORDERING','s.ordering',$listDirn,$listOrder); ?></th><th class="w-5 text-center"><?php echo HTMLHelper::_('searchtools.sort','JGRID_HEADING_ID','s.id',$listDirn,$listOrder); ?></th></tr></thead><tbody>
<?php foreach ($this->items as $i => $item) : $canEdit = $user->authorise('core.edit','com_sportsmanagement'); $canChange = $user->authorise('core.edit.state','com_sportsmanagement'); ?><tr><td class="text-center"><?php echo HTMLHelper::_('grid.id',$i,$item->id); ?></td><td><?php if ($canEdit) : ?><a href="<?php echo Route::_('index.php?option=com_sportsmanagement&task=sportstype.edit&id='.(int)$item->id); ?>"><?php echo $this->escape($item->name); ?></a><?php else : echo $this->escape($item->name); endif; ?><div class="small text-muted"><?php echo Text::_((string)$item->name); ?></div></td><td class="text-center"><?php if (!empty($item->icon)) : ?><img src="<?php echo Uri::root().ltrim($this->escape($item->icon),'/'); ?>" alt="" style="max-height:32px;max-width:48px"><?php endif; ?></td><td class="text-center"><?php echo Text::_((int)$item->sportsart === 1 ? 'COM_SPORTSMANAGEMENT_ADMIN_SPORTSART_SINGLE' : 'COM_SPORTSMANAGEMENT_ADMIN_SPORTSART_TEAM'); ?></td><td class="text-center"><?php echo HTMLHelper::_('jgrid.published',$item->published,$i,'sportstypes.',$canChange,'cb'); ?></td><td class="text-center"><input type="number" name="order[]" value="<?php echo (int)$item->ordering; ?>" class="form-control form-control-sm text-center" style="width:6rem"></td><td class="text-center"><?php echo (int)$item->id; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php echo $this->pagination->getListFooter(); ?><input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="filter_order" value="<?php echo $this->escape($listOrder); ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo $this->escape($listDirn); ?>"><?php echo HTMLHelper::_('form.token'); ?></form>
